package `in`.mubble.android.xmn

import `in`.mubble.android.core.MubbleLogger

/*------------------------------------------------------------------------------
   About      : Router to manage communication with mubble servers

   Created on : 17/01/18
   Author     : Raghvendra Varma

   Copyright (c) 2018 Mubble Networks Private Limited. All rights reserved.

--------------------------------------------------------------------------------


TODO ????

------------------------------------------------------------------------------*/


class EncProviderAndroid(private val syncKey : ByteArray,
                         private val ci      : ConnectionInfo) : MubbleLogger {

  companion object {
    // not making these thread safe as these are used once at app load time
    private var initialized = false
    private val arShortCode: ByteArray = ByteArray(4)
    private val arUniqueId: ByteArray = ByteArray(3)

    fun init(ci : ConnectionInfo) {

      if (initialized) return

      initialized = true

      val regex = Regex("[a-zA-Z0-9]{1,4}")
      var index = 0

      // Populate the application's short code
      check(ci.shortName.matches(regex))
      for (char in ci.shortName) {
        arShortCode[index++] = char.toByte().minus(40).toByte()
      }

      // Populate the unique id (version number)
      index = 0
      var parts: List<Int> = ci.uniqueId.split('.').map {it.toInt()}
      if (parts.size > 1) {
        check(parts.size == 3 && parts[0] <= 99 && parts[1] <= 99 && parts[2] <= 99)
      } else {
        var num = parts[0]
        parts   = listOf(num / 10000, num % 10000 / 100 , num % 100)
      }

      for (part in parts) arUniqueId[index++] = part.toByte()
    }

  }

  init {
    EncProviderAndroid.init(ci)
  }

  fun encodeHeader() {

    /*
      this.ci.syncKey: Sym key that is generated by client and then changed by server
      this.syncKey: Public key that is used to protect this.ci.syncKey
    */



  }



}